title: Girish Talekar
short_logo: G4T
description: |
  This is my personal websites and blogs.
baseurl: ''
url: ''
author:
  name: Girish Talekar
  github: girishg4t
  linkedin: girish-talekar-78806a66
  email: talekar.g@gmail.com
  homepage: 'https://girishg4t.github.io'
disqus_name: null
g_track_id: null
markdown: kramdown
defaults:
  - scope:
      path: _posts
    values:
      comments: true
  - scope:
      path: pages/redirects
    values:
      layout: redirect
      index: false
      listed: false
  - scope:
      path: pages/tags
    values:
      layout: tag
      sitemap:
        priority: 0.4
